### ISSUE TITLE
JVMFLAGS option not behaving as expected

### ISSUE THREAD

**Issue by gavinmcnair** [bitnami/bitnami-docker-zookeeper#40]
**Description**

The JVMFLAGS option does not appear to be working as designed.

The docs indicate

```
ZOO_HEAP_SIZE: Size in MB for the Java Heap options (Xmx and XMs). This env var is ignored if Xmx an Xms are configured via JVMFLAGS. Default: 1024
```

When i set the option using
```
                          -e "JVMFLAGS=-Xms512M -Xmx512M" \
```

Then look at my container I see
```
-Xmx1000m -Xms512M -Xmx512M 
```

Unless we are relying on JVM flag ordering to decide but this seems slightly risky and unclear.

**Comment by marcosbc** [comment]
@gavinmcnair That is because of the `ZK_SERVER_HEAP` ZooKeeper environment variable (it's officially implemented into ZooKeeper).

Note that, despite the flags being added twice, the Java server will use the rightmost values ([read more here](https://stackoverflow.com/questions/2740725/duplicated-java-runtime-options-what-is-the-order-of-preference)):

```
$ java -Xmx1024m -Xmx4024m -XX:+PrintFlagsFinal Test 2>/dev/null | grep MaxHeapSize
   size_t MaxHeapSize                              = 4219469824                                {product} {command line}
```

And according to what we're seeing, that would be Xms512M/Xmx512M, which would be correct in this scenario.

**Comment by gavinmcnair** [comment]
Fair enough. I thought that might be the case.
