### ISSUE TITLE
No newer release tag for zookeeper 3.6.2

### ISSUE THREAD

**Issue by dominiquemongelli** [bitnami/bitnami-docker-zookeeper#52]
**Description**

No newer docker image for zookeeper 3.6.2 since 6 days.

**Steps to reproduce the issue:**

The latest docker image for zookeeper 3.6.2 is the following 3.6.2-debian-10-r186. It is dated from 6 days. I'm wondering why there is not any new daily release for this version ?

**Describe the results you received:**

I'm asking this because some CVE related to curl has been raised in docker image 3.6.2-debian-10-r186 (related to package curl 7.64.0-4+deb10u1). On latest version of minideb, it has been fixed (upate to 7.64.0-4+deb10u2). So a new docker release of zookeeper should fixed those issues.

Thanks for your feedbacks.

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. The reason for not having a newer release of 3.6.2 is because the latest available version is 3.7.0. Inside a major version, we only support the latest availble (3.7.0 in this case), and that's the one that gets daily updates. If you cannot upgrade to version 3.6.2, I would suggest to rebuild the image yourselves using the Dockerfile in the repository.

https://github.com/bitnami/bitnami-docker-zookeeper/blob/9e1b321ed58630cf0e19938865cc6582dfe5954e/3/debian-10/Dockerfile

That's the commit from the 3.6.2 build.

**Comment by dominiquemongelli** [comment]
Hi,

Thanks for your answer, and pointing me the Dockerfile, I'll have a look.
Regards,

**Comment by carrodher** [comment]
Hi, we added support for tracking two branches in Zookeeper while they are being maintained by the upstream project. At this moment in the root folder of this repository, you can find two different folders (`3.6` and `3.7`), being `3.6.3` the latest version of the 3.6 branch, see https://github.com/bitnami/bitnami-docker-zookeeper#supported-tags-and-respective-dockerfile-links

**Comment by dominiquemongelli** [comment]
Hi @carrodher, actually we managed to migrate to zookeeper 3.7. Anyway, it is good to know that both versions are now supported.
