### ISSUE TITLE
Packages with Known vulnerabilities in zookeeper:3.6.3-debian-10-r87

### ISSUE THREAD

**Issue by rkandasamy-lenovo** [bitnami/bitnami-docker-zookeeper#58]
Packages with Known vulnerabilities in zookeeper:3.6.3-debian-10-r87
Refer: [zookeeper 3.6.3-debian-10-r87.pdf](https://github.com/bitnami/bitnami-docker-zookeeper/files/7083506/zookeeper.3.6.3-debian-10-r87.pdf)

![image](https://user-images.githubusercontent.com/77686255/131494793-1853f356-c2fc-4f7b-bcdd-075caec99ecf.png)

**Comment by randradas** [comment]
Thank you @rkandasamy-lenovo we will take a look to the report. It looks like there are 5 or 6 vulnerabilities to look into them. Have you experienced some issue due to them? would you be so kind to run the vulnerabilities report in 3.7.0-debian-10-r132 release? ty!

**Comment by rmkanda** [comment]
Thanks for looking into the issue @randradas. 
We have not faced any issues with this. These issues are found by our container scanners.

Latest image scan report [zookeeper 3.7.0-debian-10-r133.pdf](https://github.com/bitnami/bitnami-docker-zookeeper/files/7088720/zookeeper.3.7.0-debian-10-r133.pdf)

![image](https://user-images.githubusercontent.com/38713281/131622351-d57b2c31-25d3-406b-9d8a-d274a79fc11c.png)

**Only 7 issues are fixable:** We need to upgrade log4j and jetty library.

**Comment by randradas** [comment]
what product did you use to scan the these releases?

**Comment by rmkanda** [comment]
@randradas I used [Anchore](https://anchore.com/) Container Scan.

**Comment by randradas** [comment]
Good to know @rmkanda!

Thanks for using the Bitnami container images! Bitnami releases a new revision (-rXX) for all the container images on daily basis, see https://github.com/bitnami/bitnami-docker-zookeeper/commits/master. The main reason to follow this approach is to ensure all the bundled system packages are updated to the latest available version.

This method doesn't guarantee there are no vulnerabilities in all of them since there are some packages with known vulnerabilities that are not fixed in the Debian OS. In those cases, we can't do anything apart from wait until a new version patching the issue appears in the system package manager of the distro.
On the other hand, there is another option that is to find a vulnerability in the application code or in a library, in that case from Bitnami the only thing we can do is wait for a new upstream version to be released.

For this specific container image, you can take a look at the latest revision (-r87) in the [Quay report](https://quay.io/repository/bitnami/zookeeper/manifest/sha256:eae503e6c7ea4bfa664d3e3a3ae71e12e6419e4779862052208d6dad1ee990b5?tab=vulnerabilities) (please, ensure to click on the "Only show fixable" checkbox):

![image](https://user-images.githubusercontent.com/865380/131804912-1e3b8cdc-add6-4f40-a17d-99d47113aaf4.png)

The same validation can be executed using another CVE scanner such as Trivy:

$ trivy --ignore-unfixed --vuln-type os bitnami/zookeeper:3.6.3-debian-10-r89
2021-09-02T10:05:22.637+0200    INFO    Detecting Debian vulnerabilities...

bitnami/zookeeper:3.6.3-debian-10-r89 (debian 10.10)
====================================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)

You can find more info about Bitnami processes regarding CVEs and Vulnerability scanners at https://docs.bitnami.com/kubernetes/open-cve-policy/
